use cpu::cpu::CPU;

pub struct Instruction<'i> {
    pub dissassembly : &'static str,
    pub operand_num : u8,
    pub execute : Box<Fn(&mut CPU<'i>, u8) + 'i>,
}

impl<'i> Instruction<'i> {
    pub fn new<F: Fn(&mut CPU<'i>, u8) + 'i> (dissassembly: &'static str, operand_num : u8, func: F) -> Instruction<'i> {
        Instruction {
            dissassembly: dissassembly,
            operand_num: operand_num,
            execute: Box::new(func)
        }
    }

    pub fn execute(&mut self, cpu: &mut CPU<'i>, opcode: u8) -> u16 {
        return self.execute(cpu, opcode);
    }
}


macro_rules! inst {
    ($x:expr, $y:expr, $f:expr) => {{
        let inst = Instruction::new($x, $y, $f);
        inst
    }}    
}

#[allow(dead_code)]
pub fn create_isa <'i>() -> [Instruction<'i>; 256]{
    [
        inst!("NOP", 0, |cpu, x|{}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),         
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}),
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);}), 
        inst!("Unimp", 0, |cpu, x|{println!("Unimplemented inst with params {}", x);})
    ]
}